//! Column Box Demo
//!
//! Demonstrates pdfcrate's multi-column layout:
//! - Basic 2-column and 3-column layouts
//! - Automatic column overflow (text flows to next column)
//! - New-page overflow (when all columns are full)
//! - Custom spacer (gap between columns)
//! - Mixed content: text_wrap, text_wrap_inline in columns
//!
//! Run with: cargo run --example column_box_demo

use pdfcrate::api::Color;
use pdfcrate::prelude::{ColumnBoxOptions, Document, LayoutDocument, Margin, PageLayout, PageSize};
use pdfcrate::Result as PdfResult;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    Document::generate("column_box_demo.pdf", |doc| {
        doc.title("Column Box Demo").author("pdfcrate");
        add_page(doc)?;
        Ok(())
    })?;

    println!("Created: column_box_demo.pdf");
    Ok(())
}

/// Adds the column box demo page.
///
/// This function is also called by showcase.rs to include this page.
pub fn add_page(doc: &mut Document) -> PdfResult<()> {
    let (page_width, _) = PageSize::A4.dimensions(PageLayout::Portrait);

    // Header band
    doc.fill(|ctx| {
        ctx.gray(0.95).rectangle([0.0, 842.0], page_width, 82.0);
    });
    doc.font("Helvetica").size(24.0);
    doc.text_at("Column Box Demo", [36.0, 800.0]);
    doc.font("Helvetica").size(11.0);
    doc.text_at(
        "Multi-column layout with automatic overflow handling",
        [36.0, 780.0],
    );

    let doc_owned = std::mem::take(doc);
    let mut layout = LayoutDocument::with_margin(doc_owned, Margin::new(136.0, 36.0, 36.0, 36.0));

    let lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. \
                 Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \
                 Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris \
                 nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in \
                 reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.";

    let two_lorem = format!("{} {}", lorem, lorem);

    // Section 1: Basic 2-column layout
    layout.font("Helvetica").size(12.0);
    layout.text("1. Two-Column Layout");
    layout.move_down(8.0);

    layout.font("Helvetica").size(9.0);
    layout.column_box(ColumnBoxOptions::new(2).height(100.0), |col| {
        col.text_wrap(&two_lorem);
    });

    layout.move_down(15.0);

    // Section 2: 3-column layout
    layout.font("Helvetica").size(12.0);
    layout.text("2. Three-Column Layout");
    layout.move_down(8.0);

    layout.font("Helvetica").size(9.0);
    layout.column_box(ColumnBoxOptions::new(3).height(100.0), |col| {
        col.text_wrap(&two_lorem);
    });

    layout.move_down(15.0);

    // Section 3: Custom spacer
    layout.font("Helvetica").size(12.0);
    layout.text("3. Custom Spacer (24pt gap)");
    layout.move_down(8.0);

    layout.font("Helvetica").size(9.0);
    layout.column_box(ColumnBoxOptions::new(3).spacer(24.0).height(100.0), |col| {
        col.text_wrap(&two_lorem);
    });

    layout.move_down(15.0);

    // Section 4: Rich text in columns
    layout.font("Helvetica").size(12.0);
    layout.text("4. Rich Text in Columns (text_wrap_inline)");
    layout.move_down(8.0);

    layout.font("Helvetica").size(9.0);
    layout.column_box(ColumnBoxOptions::new(2).height(80.0), |col| {
        col.text_wrap_inline(
            "This column demonstrates <b>bold text</b>, <i>italic text</i>, and \
             <u>underlined text</u>. It also supports \
             <color rgb=\"#FF0000\">colored</color> words and \
             <font name=\"Courier\">monospace</font> segments. \
             Even E = mc<sup>2</sup> and H<sub>2</sub>O work inside columns. \
             Visit <a href=\"https://www.rust-lang.org\">Rust</a> for more.",
        );
    });

    layout.move_down(15.0);

    // Section 5: Full-page column overflow (no height limit)
    layout.font("Helvetica").size(12.0);
    layout.text("5. Column Overflow (fills remaining page)");
    layout.move_down(8.0);

    let long_text = format!("{} ", lorem).repeat(6);

    layout.font("Helvetica").size(9.0);
    layout.column_box(ColumnBoxOptions::new(3), |col| {
        col.text_wrap(&long_text);
    });

    // Footer separator
    layout.move_down(15.0);
    let rule_y = layout.cursor();
    layout.stroke(|ctx| {
        ctx.gray(0.7)
            .line_width(0.5)
            .line([36.0, rule_y], [page_width - 36.0, rule_y]);
    });
    layout.move_down(10.0);

    layout.font("Helvetica").size(9.0);
    layout
        .fill_color(Color::gray(0.4))
        .text("Generated by pdfcrate column layout engine");

    *doc = layout.into_inner();
    Ok(())
}
